const express=require('express')
const authController=require('../controllers/authController')
const router=express.Router()
router.get('/login',authController.getLogin)
router.post('/login',authController.postLogin)
router.get('/login/getEmails',authController.getEmails)
router.get('/logout',authController.postLogout)
router.get('/signup',authController.getSignup)
router.get('/signup/getEmails',authController.getEmails)
router.get('/signup/getMobile',authController.getMobileNo)
router.post('/signup',authController.postSignup)
module.exports=router